project:
  type: book

execute:
  eval: false

book:
  title: "量化投资导论"
  author: "王亚菲"
  date: "2026/8/30"
  chapters:
    - index.qmd
    - 第0章 前言1.qmd
    - 第0章 前言2.qmd
    - 第1章 基础知识 第1节 概述.qmd
    - 第1章 基础知识 第2节 理论模型.qmd
    - 第1章 基础知识 第3节 两个范式.qmd
    - 第1章 基础知识 第4节 策略研发.qmd
    - 第1章 基础知识 第6节 统计方法和模型.qmd
    - 第1章 基础知识 第7节 模型的选择.qmd
    - 第1章 基础知识 第8节 风险.qmd
    - 第1章 基础知识 第9节 编程语言.qmd
    - 第9章 风险控制 第1节 历史重大风险危机回顾.qmd
    - 第9章 风险控制 第2节 多因子风险模型的构建.qmd
    - 第16章 R 第1节 R语言入门.qmd
    - 第16章 R 第2节 数据处理.qmd
    - 第16章 R 第3节 一般统计分析.qmd
    - 第16章 R 第4节 时间序列分析.qmd
    - 第16章 R 第5节 金融计算.qmd
    - 第16章 R 第6节 线性模型.qmd



bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual
