project:
  type: book

book:
  title: "Introduction-to-Quantitative-Investment"
  author: "Norah Jones"
  date: "2026/8/30"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

